function Player (id, name, socket) {
  // id: the client id.
  // name: the name chosen by the client.
  // socket: the socket object generated by the server.
  this.id = id;
  this.name = name;
  this.socket = socket;
  this.ready = false;
};

Player.prototype.getReady = function() {
  this.ready = true;
};

Player.prototype.notReady = function() {
  this.ready = false;
};

Player.prototype.getReadyState = function() {
  return this.ready;
};

Player.prototype.getId = function() {
  return this.id;
};

Player.prototype.getName = function() {
  return this.name;
};

Player.prototype.getSocket = function() {
  return this.socket;
};

module.exports = Player;
